version: '3'
services:
  redis5:
    build: .
    ports:
      - "7005:7005"
    volumes:
      - ./docker-data/redis-cluster.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis1_app_net:
        ipv4_address: 173.17.0.7
networks:
  redis1_app_net:
    external: true
