version: '3'
services:
  redis1:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./docker-data/redis-cluster.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 172.17.0.1
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/24
