version: '3'
services:
  redis1:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis-cluster.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
