version: '3'
services:
  redis4:
    build: .
    ports:
      - "7004:7004"
    volumes:
      - ./docker-data/redis-cluster.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis1_app_net:
        ipv4_address: 173.17.0.6
networks:
  redis1_app_net:
    external: true
